/** Generación de correo y usuario interno para onboarding de trabajadores/contador. */

const PUBLIC_EMAIL_DOMAINS = new Set([
  "gmail.com",
  "googlemail.com",
  "hotmail.com",
  "outlook.com",
  "live.com",
  "yahoo.com",
  "yahoo.es",
  "icloud.com",
  "proton.me",
  "protonmail.com",
]);

export function slugifyForEmailLocalPart(nombre: string): string {
  const slug = nombre
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ".")
    .replace(/^\.+|\.+$/g, "")
    .replace(/\.{2,}/g, ".")
    .slice(0, 40);
  return slug || "usuario";
}

export function slugifyForUsuarioInterno(nombre: string): string {
  const slug = nombre
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, ".")
    .replace(/^\.+|\.+$/g, "")
    .replace(/\.{2,}/g, ".")
    .slice(0, 32);
  return slug || "usuario";
}

export function extractEmailDomain(email: string): string | null {
  const match = email.trim().toLowerCase().match(/@([^@\s]+)$/);
  return match?.[1] ?? null;
}

export function buildEmpresaEmailDomain(
  empresaEmail: string,
  nombreComercial: string,
  razonSocial: string,
): string {
  const fromEmail = extractEmailDomain(empresaEmail);
  if (fromEmail && !PUBLIC_EMAIL_DOMAINS.has(fromEmail)) {
    return fromEmail;
  }

  const base = slugifyForEmailLocalPart(nombreComercial || razonSocial || "empresa").replace(
    /\./g,
    "",
  );
  return `${base || "empresa"}.pe`;
}

export function generateUniqueEmail(
  nombre: string,
  domain: string,
  usedEmails: Iterable<string>,
): string {
  const used = new Set(
    [...usedEmails].map((email) => email.trim().toLowerCase()).filter(Boolean),
  );
  const local = slugifyForEmailLocalPart(nombre);
  let candidate = `${local}@${domain}`;
  let index = 2;
  while (used.has(candidate)) {
    candidate = `${local}${index}@${domain}`;
    index += 1;
  }
  return candidate;
}

export function generateUniqueUsuarioInterno(
  nombre: string,
  usedUsuarios: Iterable<string>,
): string {
  const used = new Set(
    [...usedUsuarios].map((value) => value.trim().toLowerCase()).filter(Boolean),
  );
  const base = slugifyForUsuarioInterno(nombre);
  let candidate = base;
  let index = 2;
  while (used.has(candidate)) {
    candidate = `${base}${index}`;
    index += 1;
  }
  return candidate;
}

export function isAutoGeneratedEmail(email: string, nombre: string, domain: string): boolean {
  const normalized = email.trim().toLowerCase();
  if (!normalized) return true;
  const local = slugifyForEmailLocalPart(nombre);
  return (
    normalized === `${local}@${domain}` ||
    new RegExp(`^${local.replace(/\./g, "\\.")}\\d*@${domain.replace(/\./g, "\\.")}$`).test(
      normalized,
    )
  );
}
