export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      clientes: {
        Row: {
          id: string;
          user_id: string;
          razon_social: string;
          ruc: string | null;
          direccion: string | null;
          telefono: string | null;
          email: string | null;
          notas: string | null;
          activo: boolean;
          contacto_nombre: string | null;
          contacto_cargo: string | null;
          segmento: string;
          estado_comercial: string;
          ejecutivo_nombre: string | null;
          ejecutivo_iniciales: string | null;
          distrito: string | null;
          fecha_alta: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          razon_social: string;
          ruc?: string | null;
          direccion?: string | null;
          telefono?: string | null;
          email?: string | null;
          notas?: string | null;
          activo?: boolean;
          contacto_nombre?: string | null;
          contacto_cargo?: string | null;
          segmento?: string;
          estado_comercial?: string;
          ejecutivo_nombre?: string | null;
          ejecutivo_iniciales?: string | null;
          distrito?: string | null;
          fecha_alta?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          razon_social?: string;
          ruc?: string | null;
          direccion?: string | null;
          telefono?: string | null;
          email?: string | null;
          notas?: string | null;
          activo?: boolean;
          contacto_nombre?: string | null;
          contacto_cargo?: string | null;
          segmento?: string;
          estado_comercial?: string;
          ejecutivo_nombre?: string | null;
          ejecutivo_iniciales?: string | null;
          distrito?: string | null;
          fecha_alta?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      productos: {
        Row: {
          id: string;
          user_id: string;
          sku: string | null;
          nombre: string;
          descripcion: string | null;
          precio: number;
          stock: number;
          unidad: string;
          activo: boolean;
          categoria: string;
          almacen: string;
          costo: number;
          tipo: string;
          stock_minimo: number;
          ultimo_movimiento_at: string;
          marca_modelo: string | null;
          afectacion_igv: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          sku?: string | null;
          nombre: string;
          descripcion?: string | null;
          precio?: number;
          stock?: number;
          unidad?: string;
          activo?: boolean;
          categoria?: string;
          almacen?: string;
          costo?: number;
          tipo?: string;
          stock_minimo?: number;
          ultimo_movimiento_at?: string;
          marca_modelo?: string | null;
          afectacion_igv?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          sku?: string | null;
          nombre?: string;
          descripcion?: string | null;
          precio?: number;
          stock?: number;
          unidad?: string;
          activo?: boolean;
          categoria?: string;
          almacen?: string;
          costo?: number;
          tipo?: string;
          stock_minimo?: number;
          ultimo_movimiento_at?: string;
          marca_modelo?: string | null;
          afectacion_igv?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          user_id: string;
          full_name: string | null;
          company_name: string | null;
          ruc: string | null;
          phone: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          full_name?: string | null;
          company_name?: string | null;
          ruc?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          full_name?: string | null;
          company_name?: string | null;
          ruc?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      orden_compra_items: {
        Row: {
          id: string;
          orden_id: string;
          producto_id: string | null;
          descripcion: string;
          cantidad: number;
          precio_unitario: number;
          subtotal: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          orden_id: string;
          producto_id?: string | null;
          descripcion: string;
          cantidad?: number;
          precio_unitario?: number;
          subtotal?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          orden_id?: string;
          producto_id?: string | null;
          descripcion?: string;
          cantidad?: number;
          precio_unitario?: number;
          subtotal?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      ordenes_compra: {
        Row: {
          id: string;
          user_id: string;
          numero: string;
          requisicion_id: string | null;
          proveedor: string;
          proveedor_ruc: string | null;
          tipo: "compra" | "servicio";
          almacen: string;
          importe: number;
          estado: "aprobada" | "emitida" | "en_transito" | "recibida" | "observada";
          categoria: "requisicion" | "orden" | "transito" | "recibida" | "observada";
          responsable: string;
          responsable_iniciales: string | null;
          notas: string | null;
          fecha_entrega_estimada: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          numero: string;
          requisicion_id?: string | null;
          proveedor: string;
          proveedor_ruc?: string | null;
          tipo?: "compra" | "servicio";
          almacen?: string;
          importe?: number;
          estado?: "aprobada" | "emitida" | "en_transito" | "recibida" | "observada";
          categoria?: "requisicion" | "orden" | "transito" | "recibida" | "observada";
          responsable: string;
          responsable_iniciales?: string | null;
          notas?: string | null;
          fecha_entrega_estimada?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          numero?: string;
          requisicion_id?: string | null;
          proveedor?: string;
          proveedor_ruc?: string | null;
          tipo?: "compra" | "servicio";
          almacen?: string;
          importe?: number;
          estado?: "aprobada" | "emitida" | "en_transito" | "recibida" | "observada";
          categoria?: "requisicion" | "orden" | "transito" | "recibida" | "observada";
          responsable?: string;
          responsable_iniciales?: string | null;
          notas?: string | null;
          fecha_entrega_estimada?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      trabajadores: {
        Row: {
          id: string;
          user_id: string;
          codigo: string | null;
          dni: string;
          nombres_apellidos: string;
          cargo: string;
          area: string;
          fecha_ingreso: string | null;
          tipo_contrato: string | null;
          sueldo_basico: number;
          regimen_laboral: string | null;
          banco: string | null;
          cuenta_sueldo: string | null;
          supervisor: string | null;
          estado: "activo" | "vacaciones" | "cesado" | "asistencia_pendiente";
          turno: string | null;
          hora_entrada: string | null;
          hora_salida: string | null;
          dias_laborables: string | null;
          dni_validado: boolean;
          es_borrador: boolean;
          asistencia_dias: number;
          asistencia_total: number;
          activo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          codigo?: string | null;
          dni: string;
          nombres_apellidos: string;
          cargo: string;
          area: string;
          fecha_ingreso?: string | null;
          tipo_contrato?: string | null;
          sueldo_basico?: number;
          regimen_laboral?: string | null;
          banco?: string | null;
          cuenta_sueldo?: string | null;
          supervisor?: string | null;
          estado?: "activo" | "vacaciones" | "cesado" | "asistencia_pendiente";
          turno?: string | null;
          hora_entrada?: string | null;
          hora_salida?: string | null;
          dias_laborables?: string | null;
          dni_validado?: boolean;
          es_borrador?: boolean;
          asistencia_dias?: number;
          asistencia_total?: number;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          codigo?: string | null;
          dni?: string;
          nombres_apellidos?: string;
          cargo?: string;
          area?: string;
          fecha_ingreso?: string | null;
          tipo_contrato?: string | null;
          sueldo_basico?: number;
          regimen_laboral?: string | null;
          banco?: string | null;
          cuenta_sueldo?: string | null;
          supervisor?: string | null;
          estado?: "activo" | "vacaciones" | "cesado" | "asistencia_pendiente";
          turno?: string | null;
          hora_entrada?: string | null;
          hora_salida?: string | null;
          dias_laborables?: string | null;
          dni_validado?: boolean;
          es_borrador?: boolean;
          asistencia_dias?: number;
          asistencia_total?: number;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      almacenes: {
        Row: {
          id: string;
          user_id: string;
          nombre: string;
          ubicacion: string | null;
          responsable: string | null;
          activo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          nombre: string;
          ubicacion?: string | null;
          responsable?: string | null;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          nombre?: string;
          ubicacion?: string | null;
          responsable?: string | null;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      oportunidades: {
        Row: {
          id: string;
          user_id: string;
          cliente_id: string | null;
          codigo: string;
          cliente_nombre: string;
          cliente_ruc: string | null;
          titulo: string;
          subtitulo: string | null;
          valor: number;
          etapa: string;
          probabilidad: number;
          responsable_nombre: string;
          responsable_iniciales: string | null;
          fecha_oportunidad: string;
          fecha_cierre_estimada: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          cliente_id?: string | null;
          codigo: string;
          cliente_nombre: string;
          cliente_ruc?: string | null;
          titulo: string;
          subtitulo?: string | null;
          valor?: number;
          etapa?: string;
          probabilidad?: number;
          responsable_nombre: string;
          responsable_iniciales?: string | null;
          fecha_oportunidad?: string;
          fecha_cierre_estimada?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          cliente_id?: string | null;
          codigo?: string;
          cliente_nombre?: string;
          cliente_ruc?: string | null;
          titulo?: string;
          subtitulo?: string | null;
          valor?: number;
          etapa?: string;
          probabilidad?: number;
          responsable_nombre?: string;
          responsable_iniciales?: string | null;
          fecha_oportunidad?: string;
          fecha_cierre_estimada?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      actividades_comerciales: {
        Row: {
          id: string;
          user_id: string;
          oportunidad_id: string | null;
          tipo: string;
          estado: string;
          titulo: string;
          fecha_programada: string | null;
          notas: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          oportunidad_id?: string | null;
          tipo: string;
          estado?: string;
          titulo: string;
          fecha_programada?: string | null;
          notas?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          oportunidad_id?: string | null;
          tipo?: string;
          estado?: string;
          titulo?: string;
          fecha_programada?: string | null;
          notas?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cotizaciones: {
        Row: {
          id: string;
          user_id: string;
          cliente_id: string | null;
          oportunidad_id: string | null;
          codigo: string;
          estado: string;
          subtotal: number;
          igv: number;
          total: number;
          moneda: string;
          validez_dias: number;
          vendedor_nombre: string | null;
          notas: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          cliente_id?: string | null;
          oportunidad_id?: string | null;
          codigo: string;
          estado?: string;
          subtotal?: number;
          igv?: number;
          total?: number;
          moneda?: string;
          validez_dias?: number;
          vendedor_nombre?: string | null;
          notas?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          cliente_id?: string | null;
          oportunidad_id?: string | null;
          codigo?: string;
          estado?: string;
          subtotal?: number;
          igv?: number;
          total?: number;
          moneda?: string;
          validez_dias?: number;
          vendedor_nombre?: string | null;
          notas?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cotizacion_items: {
        Row: {
          id: string;
          cotizacion_id: string;
          producto_id: string | null;
          descripcion: string;
          cantidad: number;
          precio_unitario: number;
          subtotal: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          cotizacion_id: string;
          producto_id?: string | null;
          descripcion: string;
          cantidad?: number;
          precio_unitario?: number;
          subtotal?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          cotizacion_id?: string;
          producto_id?: string | null;
          descripcion?: string;
          cantidad?: number;
          precio_unitario?: number;
          subtotal?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      plan_cuentas: {
        Row: {
          id: string;
          user_id: string;
          codigo: string;
          nombre: string;
          tipo: string;
          nivel: number;
          activo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          codigo: string;
          nombre: string;
          tipo: string;
          nivel?: number;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          codigo?: string;
          nombre?: string;
          tipo?: string;
          nivel?: number;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      asientos_contables: {
        Row: {
          id: string;
          user_id: string;
          codigo: string;
          fecha: string;
          hora_emision: string | null;
          glosa: string | null;
          seccion: string;
          estado: string;
          documento_ref: string | null;
          total_debe: number;
          total_haber: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          codigo: string;
          fecha?: string;
          hora_emision?: string | null;
          glosa?: string | null;
          seccion?: string;
          estado?: string;
          documento_ref?: string | null;
          total_debe?: number;
          total_haber?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          codigo?: string;
          fecha?: string;
          hora_emision?: string | null;
          glosa?: string | null;
          seccion?: string;
          estado?: string;
          documento_ref?: string | null;
          total_debe?: number;
          total_haber?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      asiento_lineas: {
        Row: {
          id: string;
          asiento_id: string;
          cuenta_codigo: string;
          cuenta_nombre: string;
          descripcion: string | null;
          debe: number | null;
          haber: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          asiento_id: string;
          cuenta_codigo: string;
          cuenta_nombre: string;
          descripcion?: string | null;
          debe?: number | null;
          haber?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          asiento_id?: string;
          cuenta_codigo?: string;
          cuenta_nombre?: string;
          descripcion?: string | null;
          debe?: number | null;
          haber?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      cuentas_cobrar: {
        Row: {
          id: string;
          user_id: string;
          cliente_id: string | null;
          venta_id: string | null;
          documento: string;
          fecha_emision: string;
          fecha_vencimiento: string;
          monto: number;
          saldo_pendiente: number;
          estado: string;
          dias_mora: number;
          notas: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          cliente_id?: string | null;
          venta_id?: string | null;
          documento: string;
          fecha_emision?: string;
          fecha_vencimiento: string;
          monto: number;
          saldo_pendiente: number;
          estado?: string;
          dias_mora?: number;
          notas?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          cliente_id?: string | null;
          venta_id?: string | null;
          documento?: string;
          fecha_emision?: string;
          fecha_vencimiento?: string;
          monto?: number;
          saldo_pendiente?: number;
          estado?: string;
          dias_mora?: number;
          notas?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cobros: {
        Row: {
          id: string;
          user_id: string;
          cuenta_cobrar_id: string;
          fecha: string;
          monto: number;
          medio_pago: string;
          referencia: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          cuenta_cobrar_id: string;
          fecha?: string;
          monto: number;
          medio_pago?: string;
          referencia?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          cuenta_cobrar_id?: string;
          fecha?: string;
          monto?: number;
          medio_pago?: string;
          referencia?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      inbox_channel_connections: {
        Row: {
          id: string;
          user_id: string;
          channel: string;
          display_name: string | null;
          external_account_id: string | null;
          config: Json;
          webhook_secret: string | null;
          access_token_encrypted: string | null;
          status: string;
          error_message: string | null;
          last_sync_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          channel: string;
          display_name?: string | null;
          external_account_id?: string | null;
          config?: Json;
          webhook_secret?: string | null;
          access_token_encrypted?: string | null;
          status?: string;
          error_message?: string | null;
          last_sync_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          channel?: string;
          display_name?: string | null;
          external_account_id?: string | null;
          config?: Json;
          webhook_secret?: string | null;
          access_token_encrypted?: string | null;
          status?: string;
          error_message?: string | null;
          last_sync_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      inbox_conversations: {
        Row: {
          id: string;
          user_id: string;
          channel: string;
          external_id: string;
          contact_name: string;
          contact_identifier: string;
          contact_avatar_url: string | null;
          last_message: string | null;
          last_message_at: string | null;
          is_read: boolean;
          stage: string;
          priority: string;
          status: string;
          advisor_name: string | null;
          advisor_initials: string | null;
          campaign: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          channel: string;
          external_id: string;
          contact_name: string;
          contact_identifier: string;
          contact_avatar_url?: string | null;
          last_message?: string | null;
          last_message_at?: string | null;
          is_read?: boolean;
          stage?: string;
          priority?: string;
          status?: string;
          advisor_name?: string | null;
          advisor_initials?: string | null;
          campaign?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          channel?: string;
          external_id?: string;
          contact_name?: string;
          contact_identifier?: string;
          contact_avatar_url?: string | null;
          last_message?: string | null;
          last_message_at?: string | null;
          is_read?: boolean;
          stage?: string;
          priority?: string;
          status?: string;
          advisor_name?: string | null;
          advisor_initials?: string | null;
          campaign?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      inbox_messages: {
        Row: {
          id: string;
          conversation_id: string;
          user_id: string;
          external_id: string | null;
          direction: string;
          body: string;
          sent_at: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          user_id: string;
          external_id?: string | null;
          direction: string;
          body: string;
          sent_at?: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          user_id?: string;
          external_id?: string | null;
          direction?: string;
          body?: string;
          sent_at?: string;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      venta_items: {
        Row: {
          id: string;
          venta_id: string;
          producto_id: string | null;
          descripcion: string;
          cantidad: number;
          precio_unitario: number;
          subtotal: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          venta_id: string;
          producto_id?: string | null;
          descripcion: string;
          cantidad?: number;
          precio_unitario?: number;
          subtotal?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          venta_id?: string;
          producto_id?: string | null;
          descripcion?: string;
          cantidad?: number;
          precio_unitario?: number;
          subtotal?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      ventas: {
        Row: {
          id: string;
          user_id: string;
          cliente_id: string | null;
          numero: string;
          fecha: string;
          estado: "borrador" | "confirmada" | "anulada";
          moneda: string;
          subtotal: number;
          igv: number;
          total: number;
          notas: string | null;
          tipo_comprobante: string;
          codigo_comprobante: string | null;
          estado_sunat: string;
          vendedor_nombre: string | null;
          vendedor_iniciales: string | null;
          tiene_cdr: boolean;
          cdr_url: string | null;
          cliente_nombre: string | null;
          cliente_ruc: string | null;
          hora_emision: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          cliente_id?: string | null;
          numero: string;
          fecha?: string;
          estado?: "borrador" | "confirmada" | "anulada";
          moneda?: string;
          subtotal?: number;
          igv?: number;
          total?: number;
          notas?: string | null;
          tipo_comprobante?: string;
          codigo_comprobante?: string | null;
          estado_sunat?: string;
          vendedor_nombre?: string | null;
          vendedor_iniciales?: string | null;
          tiene_cdr?: boolean;
          cdr_url?: string | null;
          cliente_nombre?: string | null;
          cliente_ruc?: string | null;
          hora_emision?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          cliente_id?: string | null;
          numero?: string;
          fecha?: string;
          estado?: "borrador" | "confirmada" | "anulada";
          moneda?: string;
          subtotal?: number;
          igv?: number;
          total?: number;
          notas?: string | null;
          tipo_comprobante?: string;
          codigo_comprobante?: string | null;
          estado_sunat?: string;
          vendedor_nombre?: string | null;
          vendedor_iniciales?: string | null;
          tiene_cdr?: boolean;
          cdr_url?: string | null;
          cliente_nombre?: string | null;
          cliente_ruc?: string | null;
          hora_emision?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      seed_demo_data_for_user: {
        Args: { p_user_id: string };
        Returns: undefined;
      };
    };
    Enums: Record<string, never>;
  };
};
